

defaults:
  - dataset: 2d #celeba, 2d, stackedmnist

Dataset: 2d #celeba, 2d, stackedmnist
Model : Basic # Basic, NCSN
data_dir: /data/hylia/thornton/20-schrodinger/data/
nit : 200
nit_batch : 200
npar: 10000
n_ipf_init: 1
batch_size: 10 
num_iter : 10 ** 0 + 1
n_ipf: 2 * 10 ** 0
lr: 0.0001
init_name: None
name: None

stride: 10 ** 0
g0: 10 ** -3
eps: 10 ** -1
device: cpu
